### ISSUE TITLE
Mario Odyssey not starting after deleting the smo folder and then downgrading 

### ISSUE THREAD

**Issue by Evolisches** [Istador/odyssey-downgrade#8]
I have multiple mods installed for smo and i manage them by simpling renaming the smo folder. So one day i deleted all of the smo folders and got back in the smo downgrader. After donwgrading again the game would crash. I wasnt able to fix this sadly. It works on 1.3.0. 

To reproduce this, simply delete the smo folder and downgrade the game again

**Comment by Istador** [comment]
What `smo folder` are you talking about?

This one `/atmosphere/contents/0100000000010000/`?

---

Note: some mods also write into other directories, e.g. the [SMOO](https://github.com/CraftyBoss/SuperMarioOdysseyOnline) mod is also installed to:
- `/atmosphere/exefs_patches/StarlightBase`

In this case you'd need to remove that directory too, because otherwise the game will crash on version `1.0.0` (but not on version `1.0.3`) without the other mod files inside  `/atmosphere/contents/0100000000010000/`.
